/**
 * SYMBOLIC MOMENT DOCTRINE v5.2
 * 
 * The Fundamental Operational and Philosophical Pivot of The Woven Map System
 * 
 * This document defines the transition from "predictive forecasting" to 
 * "diagnostic presence" — the geometry of the present field, not prophecy.
 */

// ============================================================================
// 1. THE DEFINITION: PRESENCE OVER PREDICTION
// ============================================================================

export const PRESENCE_DOCTRINE = `
The shift from "Symbolic Weather" to "Symbolic Moment" was enacted to correct
user expectations regarding fate and agency.

THE "NOW" VS THE "NEXT"
While "weather" implies a forecast of the future, a "Moment" describes the 
physics of the *now*. The map has never been about the future; it has always 
been about the present geometry.

THE ETHICAL SHIFT
This linguistic refinement is an ethical mandate designed to prevent users 
from "outsourcing responsibility" to the instrument. A forecast implies 
something happening *to* the user (passivity), whereas a Moment asks the 
user to *stand in it* (agency).

THE PILOT METAPHOR
The user is not a passenger checking the sky, but a **pilot consulting 
instruments** during turbulence. The relevant question is not:
  ❌ "What will happen?"
But rather:
  ✓ "What conditions exist, and can this structure handle them?"
`;

// ============================================================================
// 2. THE TEMPORAL ARCHITECTURE: CLIMATE VS. MOMENT
// ============================================================================

export const TEMPORAL_ARCHITECTURE = `
While "Symbolic Moment" is the umbrella term for the user's experience of the 
present, the system technically bifurcates this time-field into two distinct 
gauges to prevent "muddy" readings.

GAUGE A: SYMBOLIC CLIMATE (The Era/Season)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Measures the slow-moving, structural gravity — the "bass line" of experience.
Describes the "mountain you are climbing."

  • Tier 1 Architects: Pluto, Neptune, Uranus
  • Tier 2 Auditors: Saturn, Jupiter

GAUGE B: SYMBOLIC MOMENT (The Weather/Melody)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Measures the fast-moving, transient conditions — "road conditions" of the day.

  • Tier 3 Movers: Sun, Mars, Venus, Mercury
  • Tier 4 Trigger: Moon

THE HIGH-VOLTAGE WAR
By separating these, the system avoids "averaging" a crisis. It acknowledges 
that a day can have "Heavy Gravity" (Climate) even if the immediate "Wind" 
(Moment) is light, preventing the "Cancellation Error" where opposing forces 
mathematically zero each other out.
`;

/**
 * Planet tier classification for Climate vs. Moment separation.
 */
export const PLANET_TIERS = {
    // SYMBOLIC CLIMATE (slow movers)
    tier1_architects: ['Pluto', 'Neptune', 'Uranus'] as const,
    tier2_auditors: ['Saturn', 'Jupiter'] as const,

    // SYMBOLIC MOMENT (fast movers)
    tier3_movers: ['Sun', 'Mars', 'Venus', 'Mercury'] as const,
    tier4_trigger: ['Moon'] as const,
};

export const CLIMATE_PLANETS = [
    ...PLANET_TIERS.tier1_architects,
    ...PLANET_TIERS.tier2_auditors,
];

export const MOMENT_PLANETS = [
    ...PLANET_TIERS.tier3_movers,
    ...PLANET_TIERS.tier4_trigger,
];

// ============================================================================
// 3. THE METRICS: THE SEISMOGRAPH OF THE MOMENT
// ============================================================================

export const SEISMOGRAPH_DOCTRINE = `
A Symbolic Moment reading is generated by the **Balance Meter**, which 
quantifies the "physics" of the current time-field using three primary axes:

1. MAGNITUDE (The Volume)
   ━━━━━━━━━━━━━━━━━━━━━━━━
   Scale: 0–5
   Measures: Intensity of pressure on the structure
   
   High → "Peak Load" or "Storm"
   Low  → "Quiet Field"

2. DIRECTIONAL BIAS (The Flow)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Scale: –5 to +5
   Measures: Movement direction of energy
   
   Negative → COMPRESSION (inward pressure/discipline)
   Positive → EXPANSION (outward release/growth)

3. VOLATILITY (The Shake)
   ━━━━━━━━━━━━━━━━━━━━━━━━
   Scale: 0–5
   Measures: Rate of change / stability of narrative
   
   High → Multi-directional tension, fragmentation
   Low  → Coherent, single story
`;

/**
 * Metric ranges and labels for the Balance Meter.
 */
export const METRIC_RANGES = {
    magnitude: {
        scale: [0, 5] as const,
        labels: {
            0: 'Silent',
            1: 'Quiet',
            2: 'Moderate',
            3: 'Active',
            4: 'Intense',
            5: 'Peak Load / Storm',
        } as Record<number, string>,
    },
    directionalBias: {
        scale: [-5, 5] as const,
        labels: {
            negative: 'Compression (inward pressure/discipline)',
            zero: 'Equilibrium',
            positive: 'Expansion (outward release/growth)',
        },
    },
    volatility: {
        scale: [0, 5] as const,
        labels: {
            0: 'Stable / Single Story',
            1: 'Steady',
            2: 'Some Fluctuation',
            3: 'Choppy',
            4: 'Volatile',
            5: 'Chaotic / Fragmented',
        } as Record<number, string>,
    },
};

// ============================================================================
// 4. THE INTERPRETIVE FLOW: FIELD → MAP → VOICE → VALIDATION
// ============================================================================

export const INTERPRETIVE_PIPELINE = `
To read a Symbolic Moment is to practice "situational awareness" through a 
specific four-stage pipeline:

┌─────────────────────────────────────────────────────────────────────────────┐
│  FIELD (The Sensor)                                                         │
│  ━━━━━━━━━━━━━━━━━━                                                        │
│  The system detects raw atmospheric data without assigning a story.         │
│  Example: "High compression," "Volatility at 4.2"                           │
└─────────────────────────────────────────────────────────────────────────────┘
                                    ↓
┌─────────────────────────────────────────────────────────────────────────────┐
│  MAP (The Architect)                                                        │
│  ━━━━━━━━━━━━━━━━━━━                                                       │
│  The system locates *where* this pressure lands within the user's structure │
│  based on relocated coordinates.                                            │
│  Example: "The Gate (1st House)," "The Store (2nd House)"                   │
└─────────────────────────────────────────────────────────────────────────────┘
                                    ↓
┌─────────────────────────────────────────────────────────────────────────────┐
│  VOICE (The Mirror)                                                         │
│  ━━━━━━━━━━━━━━━━━━                                                        │
│  The Poetic Brain translates the geometry into Socratic inquiry.            │
│  Example: "Does this pressure feel like a wall stopping you or a demand     │
│           to shed an old skin?"                                             │
└─────────────────────────────────────────────────────────────────────────────┘
                                    ↓
┌─────────────────────────────────────────────────────────────────────────────┐
│  VALIDATION (The Audit)                                                     │
│  ━━━━━━━━━━━━━━━━━━━━━                                                     │
│  The user confirms if the reading is:                                       │
│    • WB  = Within Boundary (resonates)                                      │
│    • OSR = Outside Symbolic Range (does not apply)                          │
└─────────────────────────────────────────────────────────────────────────────┘
`;

export type ValidationResponse = 'WB' | 'OSR';

export interface PipelineStage {
    name: 'FIELD' | 'MAP' | 'VOICE' | 'VALIDATION';
    role: string;
    output: string;
}

// ============================================================================
// 5. THE CORE PRINCIPLE
// ============================================================================

export const CORE_PRINCIPLE = `
The Symbolic Moment is a "still point of precision within the moving field of time."

It replaces:
  ❌ The anxiety of "what happens next"
With:
  ✓ The structural clarity of "what is happening now"

Prioritizing:
  • CAPACITY over ease
  • PHYSICS over fate
  • PRESENCE over prediction
  • AGENCY over passivity

The user is the pilot. The system is the instrument panel.
The reading never tells you where to fly—only what the air is doing.
`;

// ============================================================================
// USAGE GUIDANCE
// ============================================================================

/**
 * Determines whether a planet contributes to Climate or Moment.
 */
export function getPlanetGauge(planet: string): 'climate' | 'moment' {
    if (CLIMATE_PLANETS.includes(planet as any)) return 'climate';
    return 'moment';
}

/**
 * Returns the appropriate frame for interpreting a reading.
 */
export function getInterpretiveFrame(magnitude: number, bias: number): string {
    if (magnitude >= 4 && bias < -2) {
        return 'Constructive Pressure — energy folding back into structure';
    }
    if (magnitude >= 4 && bias > 2) {
        return 'Expressive Surge — energy seeking outward release';
    }
    if (magnitude >= 4) {
        return 'Peak Activation — significant forces in play';
    }
    if (Math.abs(bias) < 1) {
        return 'Equilibrium — neither compression nor expansion dominates';
    }
    if (bias < -1) {
        return 'Compression Phase — inward movement, containment';
    }
    if (bias > 1) {
        return 'Expansion Phase — outward movement, growth';
    }
    return 'Quiet Field — background hum without urgent pressure';
}

/**
 * The pilot's question, not the passenger's.
 */
export const PILOT_QUESTION = 'What conditions exist, and can this structure handle them?';

// ============================================================================
// 6. VALIDATION DOCTRINE: PROOF AND AUDIT
// ============================================================================

export const VALIDATION_DOCTRINE = `
The Woven Map's philosophy concludes not with interpretation but with audit.
Every diagnostic statement must be capable of *proving its own coherence*.

Validation is the ethical echo of Presence.
To describe the moment truthfully, the system must prove it has done so.

THE SYMBOLIC SYSTEM IS ONLY MEANINGFUL IF IT CAN MEASURE ITS ACCURACY.
Meaning must remain tethered to math.
`;

/**
 * The Seven Tenets of Validation.
 * Every output must satisfy these constraints.
 */
export const VALIDATION_TENETS = {
    proportionality: {
        name: 'Proportionality',
        description: 'Interpretive intensity must scale with measured Magnitude. Language may never exceed the physics.',
        test: (magnitude: number, languageIntensity: number) => languageIntensity <= magnitude,
    },
    directionalCoherence: {
        name: 'Directional Coherence',
        description: 'The tone of any reflection must match the Directional Bias: inward-leaning geometry requires introspective phrasing; outward-leaning geometry uses expressive phrasing.',
        test: (bias: number, tonePolarity: 'inward' | 'outward' | 'neutral') => {
            if (bias < -1 && tonePolarity === 'outward') return false;
            if (bias > 1 && tonePolarity === 'inward') return false;
            return true;
        },
    },
    phaseIntegrity: {
        name: 'Phase Integrity',
        description: 'The FIELD → MAP → VOICE sequence must be preserved. "VOICE" cannot contradict "FIELD."',
    },
    falsifiability: {
        name: 'Falsifiability',
        description: 'Every narrative paragraph corresponds to measurable data (angle, orb, magnitude). The connection must be traceable.',
    },
    replicability: {
        name: 'Replicability',
        description: 'Given identical input data, the system must produce identical diagnostics. Style can vary, but structure cannot.',
    },
    auditTrail: {
        name: 'Audit Trail',
        description: 'Each generated reflection must include metadata: source JSON, computation timestamp, and Balance Meter values.',
    },
    ethicalContainment: {
        name: 'Ethical Containment',
        description: 'Interpretations may describe motion or pressure, never prescribe action. "Do" statements are forbidden; "is" statements are required.',
        forbiddenPatterns: [
            /you should/i,
            /you must/i,
            /you need to/i,
            /take action/i,
            /make sure to/i,
            /don't forget to/i,
        ],
    },
} as const;

/**
 * Validation signature for audit trails.
 * Combines magnitude, bias, volatility, and timestamp into a traceable hash.
 */
export interface ValidationSignature {
    magnitude: number;
    directionalBias: number;
    volatility: number;
    timestamp: string;
    hash: string;
}

/**
 * Generate a validation signature for a reading.
 */
export function getValidationSignature(
    magnitude: number,
    bias: number,
    volatility: number
): ValidationSignature {
    const timestamp = new Date().toISOString();
    // Simple hash combining values for traceability
    const hashInput = `${magnitude.toFixed(2)}|${bias.toFixed(2)}|${volatility.toFixed(2)}|${timestamp}`;
    const hash = hashInput.split('').reduce((acc, char) => {
        return ((acc << 5) - acc + char.charCodeAt(0)) | 0;
    }, 0).toString(16);

    return { magnitude, directionalBias: bias, volatility, timestamp, hash };
}

/**
 * Check Phase Integrity: does the VOICE layer match the FIELD layer?
 * Returns true if the language polarity matches the data polarity.
 */
export function getPhaseIntegrity(
    fieldBias: number,
    voiceTone: 'inward' | 'outward' | 'neutral'
): boolean {
    // Strong inward bias requires inward or neutral tone
    if (fieldBias < -1.5 && voiceTone === 'outward') return false;
    // Strong outward bias requires outward or neutral tone
    if (fieldBias > 1.5 && voiceTone === 'inward') return false;
    return true;
}

/**
 * Validate interpretation consistency.
 * Checks that Magnitude thresholds match adjective intensity.
 */
export function validateInterpretationConsistency(reading: {
    magnitude: number;
    bias: number;
    volatility: number;
    prose: string;
}): {
    valid: boolean;
    violations: string[];
} {
    const violations: string[] = [];
    const { magnitude, bias, prose } = reading;

    // Proportionality check: high-intensity words require high magnitude
    const highIntensityWords = ['crisis', 'explosion', 'catastrophe', 'extreme', 'overwhelming'];
    const moderateIntensityWords = ['intense', 'significant', 'strong', 'powerful'];
    const lowIntensityWords = ['gentle', 'subtle', 'quiet', 'mild', 'soft'];

    const proseLower = prose.toLowerCase();

    if (magnitude < 3) {
        for (const word of highIntensityWords) {
            if (proseLower.includes(word)) {
                violations.push(`Proportionality: "${word}" used with magnitude ${magnitude.toFixed(1)} (requires ≥4)`);
            }
        }
    }

    if (magnitude < 2) {
        for (const word of moderateIntensityWords) {
            if (proseLower.includes(word)) {
                violations.push(`Proportionality: "${word}" used with magnitude ${magnitude.toFixed(1)} (requires ≥2)`);
            }
        }
    }

    // Directional coherence check
    const inwardWords = ['contraction', 'compression', 'inward', 'consolidation', 'withdrawal'];
    const outwardWords = ['expansion', 'expression', 'outward', 'growth', 'release'];

    const hasInwardWords = inwardWords.some(w => proseLower.includes(w));
    const hasOutwardWords = outwardWords.some(w => proseLower.includes(w));

    if (bias < -2 && hasOutwardWords && !hasInwardWords) {
        violations.push(`Directional Coherence: Outward language used with strong inward bias (${bias.toFixed(1)})`);
    }
    if (bias > 2 && hasInwardWords && !hasOutwardWords) {
        violations.push(`Directional Coherence: Inward language used with strong outward bias (${bias.toFixed(1)})`);
    }

    // Ethical containment check
    for (const pattern of VALIDATION_TENETS.ethicalContainment.forbiddenPatterns) {
        if (pattern.test(prose)) {
            violations.push(`Ethical Containment: Prescriptive language detected ("${prose.match(pattern)?.[0]}")`);
        }
    }

    return {
        valid: violations.length === 0,
        violations,
    };
}

/**
 * Ensure physics-over-fate constraint.
 * Transforms any predictive phrasing into diagnostic phrasing.
 */
export function physicsOverFate(prose: string): string {
    // Replace predictive patterns with diagnostic patterns
    return prose
        .replace(/will happen/gi, 'is present')
        .replace(/will be/gi, 'appears')
        .replace(/going to/gi, 'currently')
        .replace(/you will/gi, 'the field shows')
        .replace(/this means/gi, 'this describes')
        .replace(/expect to/gi, 'may notice');
}

/**
 * Describe the present moment without forecasting.
 * Core function for Presence Doctrine compliance.
 */
export function describeNow(metrics: {
    magnitude: number;
    bias: number;
    volatility: number;
}): string {
    const frame = getInterpretiveFrame(metrics.magnitude, metrics.bias);
    const volLabel = metrics.volatility > 4 ? 'unstable rhythm' :
        metrics.volatility > 2 ? 'variable rhythm' : 'steady rhythm';

    return `The current field registers as ${frame.toLowerCase()} with ${volLabel}.`;
}

/**
 * Run the complete interpretive pipeline with validation.
 */
export function runInterpretivePipeline(input: {
    magnitude: number;
    directionalBias: number;
    volatility: number;
    chambers: string[];
    prose: string;
}): {
    stages: PipelineStage[];
    validation: ReturnType<typeof validateInterpretationConsistency>;
    signature: ValidationSignature;
} {
    const { magnitude, directionalBias, volatility, chambers, prose } = input;

    const stages: PipelineStage[] = [
        {
            name: 'FIELD',
            role: 'The Sensor',
            output: `Magnitude: ${magnitude.toFixed(1)}, Bias: ${directionalBias.toFixed(1)}, Volatility: ${volatility.toFixed(1)}`,
        },
        {
            name: 'MAP',
            role: 'The Architect',
            output: chambers.length > 0 ? `Active chambers: ${chambers.join(', ')}` : 'No specific chamber focus',
        },
        {
            name: 'VOICE',
            role: 'The Mirror',
            output: prose,
        },
        {
            name: 'VALIDATION',
            role: 'The Audit',
            output: 'Awaiting user confirmation (WB/OSR)',
        },
    ];

    const validation = validateInterpretationConsistency({
        magnitude,
        bias: directionalBias,
        volatility,
        prose,
    });

    const signature = getValidationSignature(magnitude, directionalBias, volatility);

    return { stages, validation, signature };
}

// ============================================================================
// 7. THE UNCANNY SCORE (Retrodiction)
// ============================================================================

/**
 * The Uncanny Score quantifies the "hit rate" of the map against the territory.
 * Used in retrodiction to validate system accuracy.
 * 
 * Formula: U = 100 × (1 - |M_calc - I_obs| / M_max) × C_factor
 * 
 * @param calculatedMagnitude - The magnitude the system calculated
 * @param observedIntensity - The user-reported intensity (1-5)
 * @param chamberCorrect - Whether the load hit the correct House
 */
export function calculateUncannyScore(
    calculatedMagnitude: number,
    observedIntensity: number,
    chamberCorrect: boolean
): {
    score: number;
    label: string;
    breakdown: string;
} {
    const M_max = 5;
    const C_factor = chamberCorrect ? 1.0 : 0.7;

    const accuracyComponent = 1 - Math.abs(calculatedMagnitude - observedIntensity) / M_max;
    const score = Math.round(100 * accuracyComponent * C_factor);

    let label: string;
    if (score >= 85) label = 'High Correspondence';
    else if (score >= 70) label = 'Moderate Correspondence';
    else if (score >= 50) label = 'Partial Match';
    else label = 'Low Correspondence';

    const breakdown = `Accuracy: ${(accuracyComponent * 100).toFixed(0)}% × Chamber Factor: ${C_factor} = ${score}%`;

    return { score, label, breakdown };
}

// ============================================================================
// DOCTRINE INTEGRATION TABLE
// ============================================================================

export const DOCTRINE_INTEGRATION = {
    presenceDoctrine: { function: 'describeNow', role: 'Ethical temporal orientation' },
    temporalArchitecture: { function: 'getPlanetGauge', role: 'Planetary tier structure' },
    seismographDoctrine: { function: 'getBalanceMeterValues', role: 'Measurement axes' },
    interpretivePipeline: { function: 'runInterpretivePipeline', role: 'Processing order' },
    corePrinciple: { function: 'physicsOverFate', role: 'Governing ethos' },
    validationDoctrine: { function: 'validateInterpretationConsistency', role: 'Proof and audit' },
} as const;
